package org.memory.game.gui;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import org.memory.game.logic.Constants;

/**
 *
 * @author EvanStefan
 */
public class IntroPanel extends javax.swing.JPanel {
  
  ControllerInterface controller;
  ImageIcon backgroundImageIcon;

  /**
   * Creates new form Intro
   * 
   * @param controller
   */
  public IntroPanel(ControllerInterface controller) {
    initComponents();
    this.controller = controller;
    this.backgroundImageIcon = Constants.createImageIcon(Constants.getCardBackPath());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
    newGameButton = new javax.swing.JButton();

    setMinimumSize(new java.awt.Dimension(64, 48));
    setPreferredSize(new java.awt.Dimension(640, 480));
    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    add(filler3);

    newGameButton.setText("New Game");
    newGameButton.setAlignmentX(0.5F);
    newGameButton.setMaximumSize(new java.awt.Dimension(120, 40));
    newGameButton.setMinimumSize(new java.awt.Dimension(120, 40));
    newGameButton.setPreferredSize(new java.awt.Dimension(120, 40));
    newGameButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newGameButtonActionPerformed(evt);
      }
    });
    add(newGameButton);
  }// </editor-fold>//GEN-END:initComponents

  private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
    controller.newGame();
  }//GEN-LAST:event_newGameButtonActionPerformed
  
  @Override
  public void paintComponent(Graphics g){
    super.paintComponent(g);

    ImageIcon scaled = new Scaler(
      backgroundImageIcon,
      getWidth(),
      getHeight()
    ).getScaledImageIcon();
    
    Centerer centerer = new Centerer(
      scaled.getIconWidth(), 
      scaled.getIconHeight(), 
      getWidth(), 
      getHeight() 
    );
    scaled.paintIcon(this, g, centerer.getX(), centerer.getY());
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.Box.Filler filler3;
  private javax.swing.JButton newGameButton;
  // End of variables declaration//GEN-END:variables
}
