package org.memory.game.gui;

/**
 *
 * @author EvanStefan
 */
public class NewJPanel extends javax.swing.JPanel {
  
  /**
   * Creates new form NewJPanel
   */
  public NewJPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
    jPanel4 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jComboBox3 = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jComboBox4 = new javax.swing.JComboBox<>();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
    jButton2 = new javax.swing.JButton();
    filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

    setLayout(new java.awt.GridLayout(2, 1));

    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
    jPanel1.add(filler2);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("jLabel2");
    jLabel2.setAlignmentX(0.5F);
    jLabel2.setMaximumSize(new java.awt.Dimension(200, 20));
    jLabel2.setMinimumSize(new java.awt.Dimension(40, 20));
    jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel1.add(jLabel2);

    jLabel1.setText("jLabel1: ");
    jLabel1.setAlignmentX(0.5F);
    jLabel1.setMaximumSize(new java.awt.Dimension(200, 20));
    jLabel1.setMinimumSize(new java.awt.Dimension(20, 20));
    jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel1.add(jLabel1);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setMaximumSize(new java.awt.Dimension(200, 20));
    jComboBox1.setMinimumSize(new java.awt.Dimension(20, 20));
    jComboBox1.setPreferredSize(new java.awt.Dimension(200, 20));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });
    jPanel1.add(jComboBox1);
    jPanel1.add(filler4);

    add(jPanel1);

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("jLabel5");
    jLabel5.setAlignmentX(0.5F);
    jLabel5.setMaximumSize(new java.awt.Dimension(200, 20));
    jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
    jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel4.add(jLabel5);

    jLabel3.setText("jLabel3: ");
    jLabel3.setAlignmentX(0.5F);
    jLabel3.setMaximumSize(new java.awt.Dimension(200, 20));
    jLabel3.setMinimumSize(new java.awt.Dimension(20, 20));
    jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel4.add(jLabel3);

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox3.setMaximumSize(new java.awt.Dimension(200, 20));
    jComboBox3.setMinimumSize(new java.awt.Dimension(20, 20));
    jComboBox3.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel4.add(jComboBox3);

    jLabel4.setText("jLabel4: ");
    jLabel4.setAlignmentX(0.5F);
    jLabel4.setMaximumSize(new java.awt.Dimension(200, 20));
    jLabel4.setMinimumSize(new java.awt.Dimension(20, 20));
    jLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel4.add(jLabel4);

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox4.setMaximumSize(new java.awt.Dimension(200, 20));
    jComboBox4.setMinimumSize(new java.awt.Dimension(20, 20));
    jComboBox4.setPreferredSize(new java.awt.Dimension(200, 20));
    jPanel4.add(jComboBox4);
    jPanel4.add(filler1);

    jButton2.setText("jButton2");
    jButton2.setAlignmentX(0.5F);
    jButton2.setMaximumSize(new java.awt.Dimension(120, 20));
    jButton2.setMinimumSize(new java.awt.Dimension(100, 20));
    jButton2.setPreferredSize(new java.awt.Dimension(120, 20));
    jPanel4.add(jButton2);
    jPanel4.add(filler3);

    add(jPanel4);
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBox1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.Box.Filler filler3;
  private javax.swing.Box.Filler filler4;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JComboBox<String> jComboBox4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel4;
  // End of variables declaration//GEN-END:variables
}
